"""Sync Nexi's brain from the technext.asia repo into the Nexi Studio.

Reads the live chatbot (assets/js/nexi-app.js + the page index in nexi-app.html) and writes
assets/nexi/brain.js: the same content blocks and the same matcher, wrapped so the studio can
test questions exactly the way /nexi#full answers them.

    python tools/sync_nexi_brain.py [path-to-TechNext-Website]   (default ~/ClaudeWork/TechNext-Website)
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_REPO = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/ClaudeWork/TechNext-Website')
APP_JS = os.path.join(SITE_REPO, 'assets', 'js', 'nexi-app.js')
APP_HTML = os.path.join(SITE_REPO, 'nexi-app.html')
OUT = os.path.join(ROOT, 'assets', 'nexi', 'brain.js')

src = open(APP_JS, encoding='utf-8').read().replace('\r\n', '\n')
lines = src.split('\n')


def find(pred, start=0):
    for i in range(start, len(lines)):
        if pred(lines[i]):
            return i
    raise SystemExit('pattern not found after line %d' % start)


def block(a, b):
    return '\n'.join(lines[a:b])


# 1. content: BOT_NAME .. AI_KINDS (stop before the helpers banner)
a = find(lambda l: l.startswith('var BOT_NAME'))
b = find(lambda l: l.startswith('var AI_KINDS')) + 1
content = block(a, b)
content = re.sub(r'^var SITE = .*$', 'var SITE = __SITE__;', content, flags=re.M)
if '__SITE__' not in content:
    raise SystemExit('SITE line not found')

# 2. esc / icon / oi helpers
a = find(lambda l: l.startswith('function esc('))
b = find(lambda l: l.startswith('function oi('), a) + 1
helpers = block(a, b)

# 3. KB .. TOPIC
a = find(lambda l: l.startswith('var KB = ['))
t = find(lambda l: l.startswith('var TOPIC = {'), a)
b = find(lambda l: l == '};', t) + 1
memory = block(a, b)

# 4. matcher: norm .. understand
a = find(lambda l: l.startswith('function norm('))
u = find(lambda l: l.startswith('function understand('), a)
b = find(lambda l: l == '}', u) + 1
matcher = block(a, b)

html = open(APP_HTML, encoding='utf-8').read()
m = re.search(r'<script type="application/json" id="nexi-site">(.*?)</script>', html, re.S)
site = json.loads(m.group(1)) if m else []

try:
    commit = subprocess.check_output(['git', '-C', SITE_REPO, 'log', '-1', '--format=%h %cs', '--', 'assets/js/nexi-app.js'], text=True).strip()
except Exception:
    commit = 'unknown'

body = '\n'.join([content, helpers, memory, matcher]).replace('__SITE__', json.dumps(site, ensure_ascii=False))
out = """/* GENERATED by tools/sync_nexi_brain.py from TechNext-Website assets/js/nexi-app.js (%s).
   Do not edit by hand: change the chatbot in the website repo (_src/nexi/app.html), rebuild, then re-run the sync. */
(function () {
"use strict";
%s
function byId(id){ for(var i=0;i<QUESTIONS.length;i++) if(QUESTIONS[i].id===id) return QUESTIONS[i]; return null; }
window.NEXI_BRAIN = {
  meta: { commit: %s, synced: %s },
  BOT_NAME: BOT_NAME, GREETING: GREETING, WA: WA, MEET: MEET, QUESTIONS: QUESTIONS, TOUR_KW: TOUR_KW, ICONS: ICONS,
  SITE: SITE, FACTS: FACTS, SERVICES: SERVICES, FLOW: FLOW, AI_KINDS: AI_KINDS,
  KB: KB, LABEL: LABEL, CHIP_ICON: CHIP_ICON, FOLLOW: FOLLOW, TOPIC: TOPIC,
  fn: { norm: norm, toks: toks, wordMatch: wordMatch, scoreEntry: scoreEntry, searchSite: searchSite, bestOf: bestOf, understand: understand, icon: icon, esc: esc }
};
})();
""" % (commit, body, json.dumps(commit), json.dumps(__import__('datetime').date.today().isoformat()))

# pure ASCII: escape everything else as \\uXXXX (valid in JS strings and regex literals)
out = ''.join(c if ord(c) < 128 else ('\\u%04x' % ord(c) if ord(c) < 0x10000 else
              ''.join('\\u%04x' % u for u in (0xD800 + ((ord(c) - 0x10000) >> 10), 0xDC00 + ((ord(c) - 0x10000) & 0x3FF))))
              for c in out)
open(OUT, 'w', encoding='ascii', newline='\n').write(out)
print('wrote %s (%d bytes) from %s, %d KB topics, %d site pages' % (OUT, len(out), commit, memory.count("{ id:'"), len(site)))
